version: 2.1
orbs:
  jq: circleci/jq@2.2.0
jobs:
  build:
    working_directory: ~/vault-circleci-auth-plugin
    docker:
      - image: hashicorp/vault
    steps:
      - checkout
      - jq/install
      - run:
          name: Generate nonce
          command: |
            set -e
            export VAULT_ADDR='https://hackavault-test.waypoint.run'
            vault write -format=json auth/circleci/nonce build_num="$CIRCLE_BUILD_NUM" \
              | jq '.data | {nonce: .nonce}'
      - run:
          name: Attempt to authenticate
          command: |
            set -e
            export VAULT_ADDR='https://hackavault-test.waypoint.run'
            vault write auth/circleci/login \
                project="$CIRCLE_PROJECT_REPONAME" \
                build_num="$CIRCLE_BUILD_NUM" \
                vcs_revision="$CIRCLE_SHA1"