version: 2.1

orbs:
  vault: jeffwecan/vault-auth-circleci@dev:04cf15c

references:
  urls:
    vault: &VAULT_ADDR https://hackavault-test.waypoint.run

jobs:
  lookup-token:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - attach_workspace:
          # Must be absolute path or relative path from working_directory.
          at: '~'
      - checkout
      - vault/install
      - run: vault token lookup -address='https://hackavault-test.waypoint.run'
workflows:
  main:
    jobs:
      - vault/login:
          vault-addr: *VAULT_ADDR
      - lookup-token:
          requires:
            - vault/login